In [ ]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

In [ ]:
matches = pd.read_csv("matches.csv")
deliveries = pd.read_csv("deliveries.csv")
players = pd.read_csv("players.csv")
seasons = pd.read_csv("seasons.csv")

In [ ]:
matches = matches.replace({
    "Delhi Daredevils": "Delhi Capitals",
    "Kings XI Punjab": "Punjab Kings",
    "Royal Challengers Bangalore": "Royal Challengers Bengaluru"
})

deliveries = deliveries.replace({
    "Delhi Daredevils": "Delhi Capitals",
    "Kings XI Punjab": "Punjab Kings",
    "Royal Challengers Bangalore": "Royal Challengers Bengaluru"
})

In [ ]:
print("MATCHES:", matches.shape)
print("DELIVERIES:", deliveries.shape)
print("PLAYERS:", players.shape)
print("SEASONS:", seasons.shape)

MATCHES: (1158, 25)
DELIVERIES: (134190, 18)
PLAYERS: (580, 12)
SEASONS: (18, 14)

In [ ]:
print(matches.columns.tolist())
print(deliveries.columns.tolist())
print(players.columns.tolist())
print(seasons.columns.tolist())

['match_id', 'season', 'match_number', 'stage', 'date', 'venue', 'city', 'team1', 'team2', 'toss_winner', 'toss_decision', 'first_innings_score', 'first_innings_wickets', 'first_innings_overs', 'second_innings_score', 'second_innings_wickets', 'second_innings_overs', 'result', 'winner', 'win_by', 'win_margin', 'player_of_match', 'umpire1', 'umpire2', 'is_day_night']
['delivery_id', 'match_id', 'innings', 'over', 'ball', 'batting_team', 'bowling_team', 'striker', 'non_striker', 'bowler', 'batsman_runs', 'extra_runs', 'total_runs', 'extra_type', 'is_wicket', 'dismissal_type', 'dismissed_player', 'fielder']
['player_id', 'player_name', 'nationality', 'dob_year', 'batting_style', 'bowling_style', 'playing_role', 'ipl_debut_season', 'last_season_played', 'is_capped_international', 'base_price_lakh', 'highest_auction_price_lakh']
['season', 'total_matches', 'num_teams', 'champion', 'runner_up', 'orange_cap_winner', 'purple_cap_winner', 'most_valuable_player', 'total_runs_scored', 'total_sixes', 'total_fours', 'avg_first_innings_score', 'highest_team_total', 'lowest_team_total']

In [ ]:
for name, df in {
    "matches": matches,
    "deliveries": deliveries,
    "players": players,
    "seasons": seasons
}.items():

    print(f"\n{name.upper()}")
    print(df.isnull().sum())

MATCHES
match_id                   0
season                     0
match_number               0
stage                      0
date                       0
venue                      0
city                       0
team1                      0
team2                      0
toss_winner                0
toss_decision              0
first_innings_score        0
first_innings_wickets      0
first_innings_overs        0
second_innings_score       0
second_innings_wickets     0
second_innings_overs       0
result                     0
winner                    26
win_by                    26
win_margin                 0
player_of_match            0
umpire1                    0
umpire2                    0
is_day_night               0
dtype: int64

DELIVERIES
delivery_id              0
match_id                 0
innings                  0
over                     0
ball                     0
batting_team             0
bowling_team             0
striker                  0
non_striker              0
bowler                   0
batsman_runs             0
extra_runs               0
total_runs               0
extra_type          123441
is_wicket                0
dismissal_type      126816
dismissed_player    126816
fielder             129938
dtype: int64

PLAYERS
player_id                       0
player_name                     0
nationality                     0
dob_year                        0
batting_style                   0
bowling_style                 287
playing_role                    0
ipl_debut_season                0
last_season_played              0
is_capped_international         0
base_price_lakh                 0
highest_auction_price_lakh      0
dtype: int64

SEASONS
season                     0
total_matches              0
num_teams                  0
champion                   0
runner_up                  0
orange_cap_winner          0
purple_cap_winner          0
most_valuable_player       0
total_runs_scored          0
total_sixes                0
total_fours                0
avg_first_innings_score    0
highest_team_total         0
lowest_team_total          0
dtype: int64

In [ ]:
matches = matches.drop_duplicates()
deliveries = deliveries.drop_duplicates()
players = players.drop_duplicates()
seasons = seasons.drop_duplicates()

In [ ]:
matches.columns = matches.columns.str.lower().str.strip()
deliveries.columns = deliveries.columns.str.lower().str.strip()
players.columns = players.columns.str.lower().str.strip()
seasons.columns = seasons.columns.str.lower().str.strip()

In [ ]:
all_teams = sorted(
    set(matches["team1"].dropna().unique())
    |
    set(matches["team2"].dropna().unique())
)

print("Total Teams:", len(all_teams))
print(all_teams)

Total Teams: 15
['Chennai Super Kings', 'Deccan Chargers', 'Delhi Capitals', 'Gujarat Lions', 'Gujarat Titans', 'Kochi Tuskers Kerala', 'Kolkata Knight Riders', 'Lucknow Super Giants', 'Mumbai Indians', 'Pune Warriors India', 'Punjab Kings', 'Rajasthan Royals', 'Rising Pune Supergiant', 'Royal Challengers Bengaluru', 'Sunrisers Hyderabad']

In [ ]:
match_runs = (
    deliveries
    .groupby("match_id")["total_runs"]
    .sum()
    .reset_index()
)

match_runs.columns = [
    "match_id",
    "match_total_runs"
]

match_runs.head()

  match_id  match_total_runs
0    M0001               314
1    M0002               216
2    M0003               164
3    M0004               248
4    M0005               443

In [ ]:
matches = matches.merge(
    match_runs,
    on="match_id",
    how="left"
)

matches.head()

,match_id,season,match_number,stage,date,venue,city,team1,team2,toss_winner,toss_decision,first_innings_score,first_innings_wickets,first_innings_overs,second_innings_score,second_innings_wickets,second_innings_overs,result,winner,win_by,win_margin,player_of_match,umpire1,umpire2,is_day_night,match_total_runs
0,M0001,2008,1,League,2008-03-13,Punjab Cricket Association Stadium,Mohali,Punjab Kings,Royal Challengers Bengaluru,Royal Challengers Bengaluru,bat,196,4,18.0,115,8,15.4,normal,Punjab Kings,runs,81,Moeen Taylor,Aleem Dar,Marais Erasmus,False,314
1,M0002,2008,2,League,2008-03-14,Greenfield Intl Stadium,Thiruvananthapuram,Mumbai Indians,Kolkata Knight Riders,Mumbai Indians,bat,151,4,19.2,161,3,18.6,normal,Kolkata Knight Riders,wickets,7,Shai Amla,Michael Gough,Simon Taufel,True,216
2,M0003,2008,3,League,2008-03-15,M. A. Chidambaram Stadium,Chennai,Chennai Super Kings,Mumbai Indians,Chennai Super Kings,bat,153,6,18.1,72,2,19.0,normal,Chennai Super Kings,runs,81,Lungi Warner,KN Ananthapadmanabhan,Michael Gough,True,164
3,M0004,2008,4,League,2008-03-16,DY Patil Stadium,Navi Mumbai,Chennai Super Kings,Deccan Chargers,Chennai Super Kings,field,244,4,18.3,237,1,17.4,normal,Deccan Chargers,runs,7,Denesh Cummins,Kumar Dharmasena,Simon Taufel,False,248
4,M0005,2008,5,League,2008-03-17,Sawai Mansingh Stadium,Jaipur,Rajasthan Royals,Kolkata Knight Riders,Kolkata Knight Riders,bat,236,5,18.8,205,4,15.4,normal,Kolkata Knight Riders,runs,31,Ollie Siraj,Sundaram Ravi,KN Ananthapadmanabhan,False,443

In [ ]:
matches["match_status"] = np.where(
    matches["winner"].notnull(),
    "Completed",
    "No Result"
)

In [ ]:
team_stats = (
    matches.groupby("winner")
    .agg(
        matches_won=("winner", "count")
    )
    .reset_index()
)

team_stats = team_stats.sort_values(
    "matches_won",
    ascending=False
)

team_stats.head()

                         winner  matches_won
13  Royal Challengers Bengaluru          144
10                 Punjab Kings          143
8                Mumbai Indians          130
0           Chennai Super Kings          129
6         Kolkata Knight Riders          128

In [ ]:
venue_stats = (
    matches.groupby("venue")
    .agg(
        total_matches=("match_id", "count"),
        avg_runs=("match_total_runs", "mean")
    )
    .reset_index()
)

venue_stats.head()

                  venue  total_matches    avg_runs
0  Arun Jaitley Stadium            111  261.900901
1      Barabati Stadium             31  259.161290
2     Brabourne Stadium             28  254.750000
3   Chinnaswamy Stadium            131  265.854962
4      DY Patil Stadium             22  255.681818

In [ ]:
ball_by_ball = deliveries.merge(
    matches[
        [
            "match_id",
            "season",
            "venue",
            "winner"
        ]
    ],
    on="match_id",
    how="left"
)

ball_by_ball.head()

,delivery_id,match_id,innings,over,ball,batting_team,bowling_team,striker,non_striker,bowler,batsman_runs,extra_runs,total_runs,extra_type,is_wicket,dismissal_type,dismissed_player,fielder,season,venue,winner
0,D0000001,M0001,1,1,1,Punjab Kings,Royal Challengers Bengaluru,Yuzvendra Kumar,Harry Khan,Wriddhiman Chahar,2,0,2,NaN,False,NaN,NaN,NaN,2008,Punjab Cricket Association Stadium,Punjab Kings
1,D0000002,M0001,1,1,2,Punjab Kings,Royal Challengers Bengaluru,Yuzvendra Kumar,Harry Khan,Wriddhiman Chahar,4,0,4,NaN,False,NaN,NaN,NaN,2008,Punjab Cricket Association Stadium,Punjab Kings
2,D0000003,M0001,1,1,3,Punjab Kings,Royal Challengers Bengaluru,Yuzvendra Kumar,Harry Khan,Wriddhiman Chahar,0,0,0,NaN,True,caught,Yuzvendra Kumar,Aiden Anderson,2008,Punjab Cricket Association Stadium,Punjab Kings
3,D0000004,M0001,1,1,4,Punjab Kings,Royal Challengers Bengaluru,Harry Khan,Adil Taylor,Wriddhiman Chahar,2,0,2,NaN,False,NaN,NaN,NaN,2008,Punjab Cricket Association Stadium,Punjab Kings
4,D0000005,M0001,1,1,5,Punjab Kings,Royal Challengers Bengaluru,Harry Khan,Adil Taylor,Wriddhiman Chahar,6,1,7,no-ball,False,NaN,NaN,NaN,2008,Punjab Cricket Association Stadium,Punjab Kings

In [ ]:
ball_by_ball["boundary_type"] = np.where(
    ball_by_ball["batsman_runs"].isin([4, 6]),
    "Boundary",
    "Non-Boundary"
)

In [ ]:
ball_by_ball["run_type"] = np.where(
    ball_by_ball["batsman_runs"] == 4,
    "Four",
    "Other"
)

In [ ]:
ball_by_ball["six_flag"] = np.where(
    ball_by_ball["batsman_runs"] == 6,
    "Six",
    "Other"
)

In [ ]:
ball_by_ball["ball_result"] = np.where(
    ball_by_ball["total_runs"] == 0,
    "Dot Ball",
    "Scoring Ball"
)

In [ ]:
ball_by_ball["wicket_status"] = np.where(
    ball_by_ball["is_wicket"] == 1,
    "Wicket",
    "Not Out"
)

In [ ]:
ball_by_ball["extra_status"] = np.where(
    ball_by_ball["extra_runs"] > 0,
    "Extra",
    "No Extra"
)

In [ ]:
team_matches = pd.concat([
    matches[["match_id", "team1"]]
        .rename(columns={"team1": "team"}),

    matches[["match_id", "team2"]]
        .rename(columns={"team2": "team"})
])

team_matches.head()

  match_id                 team
0    M0001         Punjab Kings
1    M0002       Mumbai Indians
2    M0003  Chennai Super Kings
3    M0004  Chennai Super Kings
4    M0005     Rajasthan Royals

In [ ]:
team_match_count = (
    team_matches.groupby("team")
    .size()
    .reset_index(name="matches_played")
)

team_match_count.head()

                  team  matches_played
0  Chennai Super Kings             239
1      Deccan Chargers              69
2       Delhi Capitals             264
3        Gujarat Lions              37
4       Gujarat Titans              49

In [ ]:
team_stats = team_stats.merge(
    team_match_count,
    left_on="winner",
    right_on="team",
    how="left"
)

team_stats["win_percentage"] = round(
    (
        team_stats["matches_won"]
        /
        team_stats["matches_played"]
    ) * 100,
    2
)

team_stats.head()

,winner,matches_won,team,matches_played,win_percentage
0,Royal Challengers Bengaluru,144,Royal Challengers Bengaluru,283,50.88
1,Punjab Kings,143,Punjab Kings,276,51.81
2,Mumbai Indians,130,Mumbai Indians,277,46.93
3,Chennai Super Kings,129,Chennai Super Kings,239,53.97
4,Kolkata Knight Riders,128,Kolkata Knight Riders,253,50.59

In [ ]:
matches.to_csv(
    "matches_clean.csv",
    index=False
)

ball_by_ball.to_csv(
    "ball_by_ball_clean.csv",
    index=False
)

team_stats.to_csv(
    "team_stats.csv",
    index=False
)

venue_stats.to_csv(
    "venue_stats.csv",
    index=False
)

In [ ]:
print("Matches:", matches.shape)
print("Ball by Ball:", ball_by_ball.shape)
print("Team Stats:", team_stats.shape)
print("Venue Stats:", venue_stats.shape)

Matches: (1158, 27)
Ball by Ball: (134190, 27)
Team Stats: (15, 5)
Venue Stats: (18, 3)